<a href="https://colab.research.google.com/github/esanilnavami-code/Daily-gym-tracker/blob/main/working_with_time_and_date.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/daily-gym-tracker/gym.csv

# NoteBook by -
## Himel Sarder
## Linkedin : linkedin.com/in/himel-sarder/

In [ ]:
df = pd.read_csv('/kaggle/input/daily-gym-tracker/gym.csv')

In [ ]:
df.head()

         Date workout     time
0  31-01-2025    walk  1:00:00
1  01-02-2025    walk  1:00:00
2  02-02-2025    walk  1:00:00
3  03-02-2025    Work        0
4  04-02-2025   Slept        0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     17 non-null     object
 1   workout  17 non-null     object
 2   time     17 non-null     object
dtypes: object(3)
memory usage: 536.0+ bytes

In [ ]:
# Converting to datetime datatype
df['Date'] = pd.to_datetime(df['Date'])

<ipython-input-5-ad7c70c8c42f>:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     17 non-null     datetime64[ns]
 1   workout  17 non-null     object
 2   time     17 non-null     object
dtypes: datetime64[ns](1), object(2)
memory usage: 536.0+ bytes

In [ ]:
df['date_year'] = df['Date'].dt.year

df.sample(5)

         Date workout     time  date_year
11 2025-02-09    Walk  0:45:00       2025
7  2025-02-06    Walk  0:45:00       2025
14 2025-02-11    Walk  0:20:00       2025
13 2025-02-11     Gym  0:45:00       2025
12 2025-02-10    Work        0       2025

In [ ]:
df['date_month'] = df['Date'].dt.month

df.sample(5)

         Date  workout     time  date_year  date_month
12 2025-02-10     Work        0       2025           2
0  2025-01-31     walk  1:00:00       2025           1
9  2025-02-07     Walk  0:20:00       2025           2
5  2025-02-05  Holiday        0       2025           2
2  2025-02-02     walk  1:00:00       2025           2

In [ ]:
df['date_day'] = df['Date'].dt.day

df.sample(5)

         Date  workout     time  date_year  date_month  date_day
5  2025-02-05  Holiday        0       2025           2         5
12 2025-02-10     Work        0       2025           2        10
9  2025-02-07     Walk  0:20:00       2025           2         7
15 2025-02-12     Walk  1:15:00       2025           2        12
2  2025-02-02     walk  1:00:00       2025           2         2

In [ ]:
df['date_month_name'] = df['Date'].dt.month_name()

df.head()

        Date workout     time  date_year  date_month  date_day date_month_name
0 2025-01-31    walk  1:00:00       2025           1        31         January
1 2025-02-01    walk  1:00:00       2025           2         1        February
2 2025-02-02    walk  1:00:00       2025           2         2        February
3 2025-02-03    Work        0       2025           2         3        February
4 2025-02-04   Slept        0       2025           2         4        February

In [ ]:
df['date_day_of_w'] = df['Date'].dt.dayofweek

df.head()

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w
0,2025-01-31,walk,1:00:00,2025,1,31,January,4
1,2025-02-01,walk,1:00:00,2025,2,1,February,5
2,2025-02-02,walk,1:00:00,2025,2,2,February,6
3,2025-02-03,Work,0,2025,2,3,February,0
4,2025-02-04,Slept,0,2025,2,4,February,1

In [ ]:
df['date_dow_name'] = df['Date'].dt.day_name()

df.sample(10)

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w,date_dow_name
9,2025-02-07,Walk,0:20:00,2025,2,7,February,4,Friday
8,2025-02-07,Gym,0:50:00,2025,2,7,February,4,Friday
0,2025-01-31,walk,1:00:00,2025,1,31,January,4,Friday
7,2025-02-06,Walk,0:45:00,2025,2,6,February,3,Thursday
6,2025-02-06,Gym,0:55:00,2025,2,6,February,3,Thursday
5,2025-02-05,Holiday,0,2025,2,5,February,2,Wednesday
4,2025-02-04,Slept,0,2025,2,4,February,1,Tuesday
1,2025-02-01,walk,1:00:00,2025,2,1,February,5,Saturday
10,2025-02-08,Work,0,2025,2,8,February,5,Saturday
13,2025-02-11,Gym,0:45:00,2025,2,11,February,1,Tuesday

In [ ]:
df['date_is_weekend'] = np.where(df['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

df.sample(10)

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w,date_dow_name,date_is_weekend
11,2025-02-09,Walk,0:45:00,2025,2,9,February,6,Sunday,1
7,2025-02-06,Walk,0:45:00,2025,2,6,February,3,Thursday,0
3,2025-02-03,Work,0,2025,2,3,February,0,Monday,0
1,2025-02-01,walk,1:00:00,2025,2,1,February,5,Saturday,1
4,2025-02-04,Slept,0,2025,2,4,February,1,Tuesday,0
2,2025-02-02,walk,1:00:00,2025,2,2,February,6,Sunday,1
12,2025-02-10,Work,0,2025,2,10,February,0,Monday,0
14,2025-02-11,Walk,0:20:00,2025,2,11,February,1,Tuesday,0
10,2025-02-08,Work,0,2025,2,8,February,5,Saturday,1
6,2025-02-06,Gym,0:55:00,2025,2,6,February,3,Thursday,0

In [ ]:
df['date_quarter'] = df['Date'].dt.quarter

df.sample(10)

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w,date_dow_name,date_is_weekend,date_quarter
12,2025-02-10,Work,0,2025,2,10,February,0,Monday,0,1
8,2025-02-07,Gym,0:50:00,2025,2,7,February,4,Friday,0,1
7,2025-02-06,Walk,0:45:00,2025,2,6,February,3,Thursday,0,1
14,2025-02-11,Walk,0:20:00,2025,2,11,February,1,Tuesday,0,1
10,2025-02-08,Work,0,2025,2,8,February,5,Saturday,1,1
5,2025-02-05,Holiday,0,2025,2,5,February,2,Wednesday,0,1
6,2025-02-06,Gym,0:55:00,2025,2,6,February,3,Thursday,0,1
4,2025-02-04,Slept,0,2025,2,4,February,1,Tuesday,0,1
1,2025-02-01,walk,1:00:00,2025,2,1,February,5,Saturday,1,1
13,2025-02-11,Gym,0:45:00,2025,2,11,February,1,Tuesday,0,1

In [ ]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2025, 2, 15, 4, 19, 21, 498046)

In [ ]:
today - df['Date']

0    15 days 04:19:21.498046
1    14 days 04:19:21.498046
2    13 days 04:19:21.498046
3    12 days 04:19:21.498046
4    11 days 04:19:21.498046
5    10 days 04:19:21.498046
6     9 days 04:19:21.498046
7     9 days 04:19:21.498046
8     8 days 04:19:21.498046
9     8 days 04:19:21.498046
10    7 days 04:19:21.498046
11    6 days 04:19:21.498046
12    5 days 04:19:21.498046
13    4 days 04:19:21.498046
14    4 days 04:19:21.498046
15    3 days 04:19:21.498046
16    2 days 04:19:21.498046
Name: Date, dtype: timedelta64[ns]

In [ ]:
(today - df['Date']).dt.days

0     15
1     14
2     13
3     12
4     11
5     10
6      9
7      9
8      8
9      8
10     7
11     6
12     5
13     4
14     4
15     3
16     2
Name: Date, dtype: int64

In [ ]:
print(df[df['time'] == '0'])

         Date  workout time  date_year  date_month  date_day date_month_name  \
3  2025-02-03     Work    0       2025           2         3        February
4  2025-02-04    Slept    0       2025           2         4        February
5  2025-02-05  Holiday    0       2025           2         5        February
10 2025-02-08     Work    0       2025           2         8        February
12 2025-02-10     Work    0       2025           2        10        February
16 2025-02-13  Holiday    0       2025           2        13        February

    date_day_of_w date_dow_name  date_is_weekend  date_quarter
3               0        Monday                0             1
4               1       Tuesday                0             1
5               2     Wednesday                0             1
10              5      Saturday                1             1
12              0        Monday                0             1
16              3      Thursday                0             1

In [ ]:
print(df.dtypes)

Date               datetime64[ns]
workout                    object
time                       object
date_year                   int32
date_month                  int32
date_day                    int32
date_month_name            object
date_day_of_w               int32
date_dow_name              object
date_is_weekend             int64
date_quarter                int32
dtype: object

In [ ]:
df['time'] = df['time'].astype(str)

In [ ]:
df.dtypes

Date               datetime64[ns]
workout                    object
time                       object
date_year                   int32
date_month                  int32
date_day                    int32
date_month_name            object
date_day_of_w               int32
date_dow_name              object
date_is_weekend             int64
date_quarter                int32
dtype: object

In [ ]:
df['time'] = df['time'].replace('0', '00:00:00')

df.head()

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w,date_dow_name,date_is_weekend,date_quarter
0,2025-01-31,walk,1:00:00,2025,1,31,January,4,Friday,0,1
1,2025-02-01,walk,1:00:00,2025,2,1,February,5,Saturday,1,1
2,2025-02-02,walk,1:00:00,2025,2,2,February,6,Sunday,1,1
3,2025-02-03,Work,00:00:00,2025,2,3,February,0,Monday,0,1
4,2025-02-04,Slept,00:00:00,2025,2,4,February,1,Tuesday,0,1

In [ ]:
df['time'] = pd.to_datetime(df['time'], format='%H:%M:%S', errors='coerce').dt.time

In [ ]:
df

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w,date_dow_name,date_is_weekend,date_quarter
0,2025-01-31,walk,01:00:00,2025,1,31,January,4,Friday,0,1
1,2025-02-01,walk,01:00:00,2025,2,1,February,5,Saturday,1,1
2,2025-02-02,walk,01:00:00,2025,2,2,February,6,Sunday,1,1
3,2025-02-03,Work,00:00:00,2025,2,3,February,0,Monday,0,1
4,2025-02-04,Slept,00:00:00,2025,2,4,February,1,Tuesday,0,1
5,2025-02-05,Holiday,00:00:00,2025,2,5,February,2,Wednesday,0,1
6,2025-02-06,Gym,00:55:00,2025,2,6,February,3,Thursday,0,1
7,2025-02-06,Walk,00:45:00,2025,2,6,February,3,Thursday,0,1
8,2025-02-07,Gym,00:50:00,2025,2,7,February,4,Friday,0,1
9,2025-02-07,Walk,00:20:00,2025,2,7,February,4,Friday,0,1
10,2025-02-08,Work,00:00:00,2025,2,8,February,5,Saturday,1,1
11,2025-02-09,Walk,00:45:00,2025,2,9,February,6,Sunday,1,1
12,2025-02-10,Work,00:00:00,2025,2,10,February,0,Monday,0,1
13,2025-02-11,Gym,00:45:00,2025,2,11,February,1,Tuesday,0,1
14,2025-02-11,Walk,00:20:00,2025,2,11,February,1,Tuesday,0,1
15,2025-02-12,Walk,01:15:00,2025,2,12,February,2,Wednesday,0,1
16,2025-02-13,Holiday,00:00:00,2025,2,13,February,3,Thursday,0,1

In [ ]:
df['hour'] = df['time'].apply(lambda t: t.hour)
df['minute'] = df['time'].apply(lambda t: t.minute)
df['second'] = df['time'].apply(lambda t: t.second)

In [ ]:
df

,Date,workout,time,date_year,date_month,date_day,date_month_name,date_day_of_w,date_dow_name,date_is_weekend,date_quarter,hour,minute,second
0,2025-01-31,walk,01:00:00,2025,1,31,January,4,Friday,0,1,1,0,0
1,2025-02-01,walk,01:00:00,2025,2,1,February,5,Saturday,1,1,1,0,0
2,2025-02-02,walk,01:00:00,2025,2,2,February,6,Sunday,1,1,1,0,0
3,2025-02-03,Work,00:00:00,2025,2,3,February,0,Monday,0,1,0,0,0
4,2025-02-04,Slept,00:00:00,2025,2,4,February,1,Tuesday,0,1,0,0,0
5,2025-02-05,Holiday,00:00:00,2025,2,5,February,2,Wednesday,0,1,0,0,0
6,2025-02-06,Gym,00:55:00,2025,2,6,February,3,Thursday,0,1,0,55,0
7,2025-02-06,Walk,00:45:00,2025,2,6,February,3,Thursday,0,1,0,45,0
8,2025-02-07,Gym,00:50:00,2025,2,7,February,4,Friday,0,1,0,50,0
9,2025-02-07,Walk,00:20:00,2025,2,7,February,4,Friday,0,1,0,20,0
10,2025-02-08,Work,00:00:00,2025,2,8,February,5,Saturday,1,1,0,0,0
11,2025-02-09,Walk,00:45:00,2025,2,9,February,6,Sunday,1,1,0,45,0
12,2025-02-10,Work,00:00:00,2025,2,10,February,0,Monday,0,1,0,0,0
13,2025-02-11,Gym,00:45:00,2025,2,11,February,1,Tuesday,0,1,0,45,0
14,2025-02-11,Walk,00:20:00,2025,2,11,February,1,Tuesday,0,1,0,20,0
15,2025-02-12,Walk,01:15:00,2025,2,12,February,2,Wednesday,0,1,1,15,0
16,2025-02-13,Holiday,00:00:00,2025,2,13,February,3,Thursday,0,1,0,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             17 non-null     datetime64[ns]
 1   workout          17 non-null     object
 2   time             17 non-null     object
 3   date_year        17 non-null     int32
 4   date_month       17 non-null     int32
 5   date_day         17 non-null     int32
 6   date_month_name  17 non-null     object
 7   date_day_of_w    17 non-null     int32
 8   date_dow_name    17 non-null     object
 9   date_is_weekend  17 non-null     int64
 10  date_quarter     17 non-null     int32
 11  hour             17 non-null     int64
 12  minute           17 non-null     int64
 13  second           17 non-null     int64
dtypes: datetime64[ns](1), int32(5), int64(4), object(4)
memory usage: 1.7+ KB